name: deploy
on:
  push:
    branches:
      - main
env:
  VERSION_FILE: ./package.json
  VERSION_EXTRACT_PATTERN: '"version": "([^"]+)",'
jobs:
  deploy:
    name: deploy
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: npm version patch
      - name: Version
        uses: HardNorth/github-version-generate@v1.0.2
        with:
          version-source: file
          version-file: ${{ env.VERSION_FILE }}
          version-file-extraction-pattern: ${{ env.VERSION_EXTRACT_PATTERN }}
      - name: Tag
        run: |
          git push origin v${{ env.RELEASE_VERSION }}
      - name: Build
        uses: actions/setup-node@v1
        with:
          node-version: '20.x'
      - run: yarn install
      - run: yarn build
      - name: Checkout to gh-pages
        run: |
          git fetch origin
          git checkout gh-pages
      - run: npm --no-git-tag-version version patch
      - name: Version
        uses: HardNorth/github-version-generate@v1.0.2
        with:
          version-source: file
          version-file: ${{ env.VERSION_FILE }}
          version-file-extraction-pattern: ${{ env.VERSION_EXTRACT_PATTERN }}
      - name: Move to directory
        run: |
          git reset HEAD~
          mv package.json build/
          rm -f .eslintcache *.html *.ico *.json *.png *.txt
          rm -rf static/
          mv build/* ./
      - name: Add & Commit
        run: |
          git add -- . ':!build' ':!node_modules'
          git commit -m "Release: v${{ env.RELEASE_VERSION }}"
          git push origin gh-pages
